import type { Incident, User } from './types';

export const mockUsers: Record<string, User> = {
  admin: {
    name: 'Admin User',
    email: 'admin@samridhi.watch',
    role: 'admin',
    avatar: 'https://i.pravatar.cc/150?u=admin',
  },
  authority: {
    name: 'Authority User',
    email: 'authority@samridhi.watch',
    role: 'authority',
    avatar: 'https://i.pravatar.cc/150?u=authority',
  },
  viewer: {
    name: 'Read-Only Viewer',
    email: 'viewer@samridhi.watch',
    role: 'viewer',
    avatar: 'https://i.pravatar.cc/150?u=viewer',
  },
};

export const mockIncidents: Incident[] = [
  {
    id: 'INC001',
    type: 'Fire',
    severity: 'critical',
    location: 'Downtown Plaza',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    confidence: 95,
    posts: ['post1', 'post2', 'post3'],
    status: 'new',
    summary: 'A critical fire incident has been reported at Downtown Plaza, multiple sources confirm.',
  },
  {
    id: 'INC002',
    type: 'Accident',
    severity: 'severe',
    location: 'Highway 101, Exit 4A',
    coordinates: { lat: 34.0600, lng: -118.2500 },
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    confidence: 88,
    posts: ['post4', 'post5'],
    status: 'acknowledged',
    summary: 'Multi-vehicle accident on Highway 101 causing major traffic disruption. Emergency services on scene.',
  },
  {
    id: 'INC003',
    type: 'Congestion',
    severity: 'moderate',
    location: 'Central Bridge',
    coordinates: { lat: 34.0550, lng: -118.2400 },
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    confidence: 92,
    posts: ['post6'],
    status: 'in-progress',
    summary: 'Severe traffic congestion on Central Bridge due to an earlier accident. Authorities are managing traffic flow.',
  },
  {
    id: 'INC004',
    type: 'Public Unrest',
    severity: 'moderate',
    location: 'City Hall Park',
    coordinates: { lat: 34.0530, lng: -118.2445 },
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    confidence: 75,
    posts: ['post7', 'post8'],
    status: 'resolved',
    summary: 'A protest at City Hall Park has been peacefully resolved. Crowds have dispersed.',
  },
  {
    id: 'INC005',
    type: 'Fire',
    severity: 'minor',
    location: 'Suburban District 5',
    coordinates: { lat: 34.0700, lng: -118.2300 },
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    confidence: 98,
    posts: ['post9'],
    status: 'resolved',
    summary: 'A small dumpster fire in Suburban District 5 was quickly extinguished. No injuries or major damage.',
  },
   {
    id: 'INC006',
    type: 'Accident',
    severity: 'severe',
    location: 'Oak Street & 4th Ave',
    coordinates: { lat: 34.0488, lng: -118.2522 },
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    confidence: 91,
    posts: ['post10', 'post11', 'post12'],
    status: 'new',
    summary: 'Reports of a major collision involving a public bus at Oak and 4th. Emergency response needed.',
  },
];
